name: Terraform Plan and Apply

on:
  pull_request:
    paths:
      - 'terraform/**'
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: 'terraform/live'
    permissions:
      pull-requests: write
      id-token: write
    steps:
      - uses: actions/checkout@v4
      - uses: engineerd/setup-kind@v0.6.2 
      - uses: hashicorp/setup-terraform@v3

      - name: Terraform fmt
        if: github.event_name == 'pull_request'
        id: fmt
        run: terraform fmt -check
        continue-on-error: true

      - name: Terraform Init
        if: github.event_name == 'pull_request'
        id: init
        run: terraform init -input=false

      - name: Terraform Validate
        if: github.event_name == 'pull_request'
        id: validate
        run: terraform validate -no-color

      - name: Terraform Plan
        if: github.event_name == 'pull_request'
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true

      - uses: actions/github-script@v7
        if: github.event_name == 'pull_request'
        env:
          PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
            #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
            #### Terraform Validation 🤖\`${{ steps.validate.outcome }}\`
            <details><summary>Validation Output</summary>

            \`\`\`\n
            ${{ steps.validate.outputs.stdout }}
            \`\`\`

            </details>

            #### Terraform Plan 📖\`${{ steps.plan.outcome }}\`

            <details><summary>Show Plan</summary>

            \`\`\`\n
            ${process.env.PLAN}
            \`\`\`

            </details>

            *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`terraform/live\`, Workflow: \`${{ github.workflow }}\`*`;

            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: output
            })

      - name: Terraform Apply
        if: github.event_name == 'pull_request'
        id: apply
        run: terraform apply -auto-approve
        continue-on-error: true

      - name: Get Pods
        if: github.event_name == 'pull_request'
        id: get-pods
        run: |
          # Get all pods and their status
          pods=$(kubectl get pods -n default -o json)
          
          # Check each pod's status
          not_ready_pods=$(echo "$pods" | jq -r '.items[] | select(.status.phase != "Running") | .metadata.name')
          
          if [ ! -z "$not_ready_pods" ]; then
            echo "Found pods not in Running state:"
            for pod in $not_ready_pods; do
              echo "=== Details for $pod ==="
              kubectl describe pod $pod -n default
              echo "====================="
            done
            echo "pod_status=not_ready" >> $GITHUB_OUTPUT
          else
            echo "All pods are running"
            echo "pod_status=ready" >> $GITHUB_OUTPUT
          fi

      - name: Check Apply Status
        if: github.event_name == 'pull_request'
        id: check_apply
        run: |
          if [ "${{ steps.apply.outcome }}" == "success" ]; then
            echo "apply_status=success" >> $GITHUB_OUTPUT
          else
            echo "apply_status=failure" >> $GITHUB_OUTPUT
          fi


      - name: Install dependencies
        if: steps.check_apply.outputs.apply_status == 'success' && steps.get-pods.outputs.pod_status == 'ready'
        run: |
          python -m pip install --upgrade pip
          pip install requests
  
      - name: Run E2E Test Script
        if: steps.check_apply.outputs.apply_status == 'success' && steps.get-pods.outputs.pod_status == 'ready'
        run: |
          python e2e/test_load_balancing.py --url=http://localhost:8081 --requests=20 --delay=1.0

      - name: Verify Load Balancing Output
        if: steps.check_apply.outputs.apply_status == 'success' && steps.get-pods.outputs.pod_status == 'ready'
        run: |
          # Optionally, check if the Python script output is as expected
          # Example: Grep for expected message in logs
          echo "Verifying load balancing test results..."
          python e2e/test_load_balancing.py --url=http://localhost:80 --requests=20 --delay=1.0 | tee result.log
          if grep -q "Load balancing appears to be working!" result.log; then
            echo "Load balancing is working correctly."
          else
            echo "Load balancing test failed."
            exit 1
          fi
